services:
  app:
    container_name: subfloor-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Don't restart endlessly in dev if it crashes
    restart: "no" 
    # Map Host Port (defined in .env or default 5173 for dev) -> Container 3001
    ports:
      - "${PORT:-5173}:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - ./server/uploads:/app/server/uploads
    depends_on:
          db:
            condition: service_healthy
    networks:
      - app-network-dev

  db:
    container_name: subfloor-db-dev
    image: postgres:17-alpine
    restart: "no"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # CRITICAL: Different volume name so it doesn't share data with Prod
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - app-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  supertokens:
    container_name: subfloor-supertokens-dev
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
      API_KEY: ${SUPERTOKENS_API_KEY}
    networks:
      - app-network-dev

networks:
  app-network-dev:
    driver: bridge

volumes:
  # This creates a distinct volume named [project]_postgres_data_dev
  postgres_data_dev: