services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: subfloor_server
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/temp-uploads:/app/temp-uploads
      - ./server:/app
      - /app/node_modules
    ports:
      - "192.168.1.10:3001:3001"
    env_file:
      - ./.env 
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/supertokens
      - SUPERTOKENS_CONNECTION_URI=http://supertokens:3567
      - SUPERTOKENS_API_KEY=some-long-and-secure-key
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      supertokens:
        condition: service_started

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subfloor_app
    ports:
      - "192.168.1.10:5173:5173"
    volumes:
      # Mount entire frontend project
      - .:/app

      # Keep node_modules internal so Tailwind and Vite plugins install correctly
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - server
      - supertokens
    command: npm run dev

  supertokens:
    image: supertokens/supertokens-postgresql:11.2
    container_name: subfloor_supertokens
    ports:
      - "3567:3567"
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=supertokens
      - SUPERTOKENS_API_KEY=some-long-and-secure-key
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: subfloor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=supertokens
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    external: true
    name: joblogger_postgres_data
